In [1]:
import requests, webbrowser
from bs4 import BeautifulSoup
import os 
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
from pathlib import Path
import math
from sklearn.feature_extraction import text
import random

In [2]:
folder_names = []
all_files = []
count = 0
path = os.getcwd() + "/Datasets"
for dirpath, dirnames, filenames in os.walk(path):  # getcwd() for current work dir
    if count == 0:
        folder_names = dirnames
    else:
        all_files.append(filenames)
    count+=1

In [3]:
text_seperate = []
text_all = []

for i in range(len(all_files)):
    text_folder = []
    text_documents = ""
    for file_name in all_files[i]:
        txt = Path(path+"/"+folder_names[i]+"/"+file_name).read_text()
        txt = txt.replace("\n", " ")
        txt = txt.replace("\t", " ")
        text_documents += txt
        text_folder.append(txt)
    text_all.append(text_documents)
    text_seperate.append(text_folder)

In [4]:
new_text_all = []
for i in range(len(text_all)):
    txt = text_all[i].lower().split()
    new_text = ""
    for word in txt:
        occurence = txt.count(word)
        doc_with_word = 0
        for doc in text_seperate[i]:
            if word in doc:
                doc_with_word += 1
        
        if occurence >= 30 and doc_with_word >=8:
            new_text += word + " "
    new_text_all.append(new_text)

In [5]:
vectorizer_1 = TfidfVectorizer(stop_words = text.ENGLISH_STOP_WORDS)
vectors = vectorizer_1.fit_transform([new_text_all[0]])
feature_names_1 = vectorizer_1.get_feature_names()

In [6]:
vectorizer_2 = TfidfVectorizer(stop_words = text.ENGLISH_STOP_WORDS)
vectors = vectorizer_2.fit_transform([new_text_all[1]])
feature_names_2 = vectorizer_2.get_feature_names()

In [7]:
vectorizer_3 = TfidfVectorizer(stop_words = text.ENGLISH_STOP_WORDS)
vectors = vectorizer_3.fit_transform([new_text_all[2]])
feature_names_3 = vectorizer_3.get_feature_names()

In [8]:
feature_names = []
feature_names.append(feature_names_1)
feature_names.append(feature_names_2)
feature_names.append(feature_names_3)

In [9]:
features_all = []

for i in range(len(feature_names)):
    feature_topic = []
    for feature in feature_names[i]:
        counter = False
        if not feature.isdigit():
            for char in feature:
                if char.isdigit():
                    counter = True
                    break
            if not counter:
                feature_topic.append(feature)
    features_all.append(feature_topic)

In [10]:
len(features_all[0])

93

In [11]:
len(features_all[1])

37

In [12]:
len(features_all[2])

39

In [13]:
selected_feature_all = []
selected_num_all = []

for i in range(len(features_all)):
    
    count = 0
    feature_list = features_all[i]
    max_num = len(feature_list)-1
    
    selected_feature = []
    selected_num = []
    
    while count < 15:
        num = random.randint(0,max_num)
        if num not in selected_num:
            selected_feature.append(feature_list[num])
            selected_num.append(num)
            count += 1
    selected_feature_all.append(selected_feature)
    selected_num_all.append(selected_num)

In [14]:
tfidf_all_1 = []
occurences_all_1 = []
for data in text_seperate[0]:
    doc_tfidf = []
    doc_occurences = []
    for feature in selected_feature_all[0]:
        occurences = data.count(feature)
        doc_occurences.append(occurences)
        num_words = len(data.split())
        tf = occurences/num_words
        doc_with_feature = 0
        idf = 0
        for doc in text_seperate[0]:
            if feature in doc:
                doc_with_feature += 1
        if doc_with_feature != 0:
            idf = math.log((10/doc_with_feature),2)
        tfidf = tf*idf
        doc_tfidf.append(tfidf)
    tfidf_all_1.append(doc_tfidf)
    occurences_all_1.append(doc_occurences)

In [15]:
df_1 = pd.DataFrame(tfidf_all_1)
df_1.columns = selected_feature_all[0]
df_1

,mit,best,network,work,systems,risk,based,algorithms,software,computing,people,technology,know,humans,given
0,0.0,0.000000,0.000000,0.0,0.0,0.000307,0.000362,0.000797,0.001227,0.000000,0.000507,0.000145,0.000145,0.0,0.000153
1,0.0,0.000056,0.000184,0.0,0.0,0.000011,0.000225,0.000084,0.000044,0.000089,0.000010,0.000026,0.000362,0.0,0.000577
2,0.0,0.000242,0.000400,0.0,0.0,0.000000,0.000000,0.000228,0.000121,0.000363,0.000000,0.000114,0.000285,0.0,0.000121
3,0.0,0.000397,0.000590,0.0,0.0,0.000114,0.000214,0.000188,0.000227,0.000114,0.000241,0.000134,0.000214,0.0,0.000170
4,0.0,0.000168,0.000053,0.0,0.0,0.000729,0.000053,0.000026,0.000112,0.000168,0.000318,0.000344,0.000265,0.0,0.000056
5,0.0,0.000233,0.000495,0.0,0.0,0.000116,0.000055,0.000385,0.000582,0.000466,0.000055,0.000110,0.000055,0.0,0.000116
6,0.0,0.000284,0.000134,0.0,0.0,0.000057,0.000080,0.000241,0.000284,0.000227,0.000161,0.000429,0.000215,0.0,0.000284
7,0.0,0.000000,0.000479,0.0,0.0,0.000000,0.000120,0.000000,0.000000,0.000253,0.000120,0.000000,0.000479,0.0,0.000000
8,0.0,0.000246,0.000116,0.0,0.0,0.000246,0.000233,0.000116,0.000000,0.000000,0.000582,0.000233,0.000000,0.0,0.000000
9,0.0,0.000070,0.000442,0.0,0.0,0.000332,0.000176,0.000166,0.000141,0.000292,0.000114,0.000104,0.000451,0.0,0.000070

In [16]:
tfidf_all_2 = []
occurences_all_2 = []
for data in text_seperate[1]:
    doc_tfidf = []
    doc_occurences = []
    for feature in selected_feature_all[1]:
        occurences = data.count(feature)
        doc_occurences.append(occurences)
        num_words = len(data.split())
        tf = occurences/num_words
        doc_with_feature = 0
        idf = 0
        
        for doc in text_seperate[1]:
            if feature in doc:
                doc_with_feature += 1
        if doc_with_feature != 0:
            idf = math.log((10/doc_with_feature),2)
        tfidf = tf*idf
        doc_tfidf.append(tfidf)
    tfidf_all_2.append(doc_tfidf)
    occurences_all_2.append(doc_occurences)

In [17]:
df_2 = pd.DataFrame(tfidf_all_2)
df_2.columns = selected_feature_all[1]
df_2

,financial,transactions,way,applications,block,business,make,change,digital,private,public,chain,crypto,cryptocurrency,peer
0,0.000025,0.0,0.000273,0.000263,0.0,0.000273,0.000894,0.0,0.000348,0.000526,0.000999,0.0,0.0,0.000124,0.000210
1,0.000290,0.0,0.000579,0.000123,0.0,0.000463,0.000368,0.0,0.000058,0.000491,0.000368,0.0,0.0,0.000348,0.000736
2,0.000225,0.0,0.000501,0.000424,0.0,0.000150,0.000955,0.0,0.000150,0.000159,0.000371,0.0,0.0,0.000200,0.001804
3,0.000172,0.0,0.000344,0.000000,0.0,0.000172,0.000365,0.0,0.000344,0.001094,0.001094,0.0,0.0,0.000344,0.000000
4,0.001039,0.0,0.000390,0.000550,0.0,0.000520,0.000000,0.0,0.000260,0.000000,0.000000,0.0,0.0,0.001039,0.000550
5,0.000218,0.0,0.000435,0.000461,0.0,0.000145,0.000461,0.0,0.000290,0.000154,0.000307,0.0,0.0,0.000363,0.000307
6,0.000101,0.0,0.000134,0.000142,0.0,0.000067,0.000107,0.0,0.000202,0.000925,0.000890,0.0,0.0,0.000235,0.000534
7,0.000135,0.0,0.000471,0.000285,0.0,0.000876,0.000713,0.0,0.000135,0.000571,0.000713,0.0,0.0,0.000135,0.000285
8,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
9,0.000187,0.0,0.000312,0.001650,0.0,0.000592,0.000198,0.0,0.000343,0.000594,0.000396,0.0,0.0,0.000062,0.000330

In [18]:
tfidf_all_3 = []
occurences_all_3 = []
for data in text_seperate[2]:
    doc_tfidf = []
    doc_occurences = []
    for feature in selected_feature_all[2]:
        occurences = data.count(feature)
        doc_occurences.append(occurences)
        num_words = len(data.split())
        tf = occurences/num_words
        doc_with_feature = 0
        idf = 0
        
        for doc in text_seperate[2]:
            if feature in doc:
                doc_with_feature += 1
        if doc_with_feature != 0:
            idf = math.log((10/doc_with_feature),2)
        tfidf = tf*idf
        doc_tfidf.append(tfidf)
    tfidf_all_3.append(doc_tfidf)
    occurences_all_3.append(doc_occurences)

In [19]:
df_3 = pd.DataFrame(tfidf_all_3)
df_3.columns = selected_feature_all[2]
df_3

,machine,using,add,devices,like,networks,connected,business,know,smart,network,sensor,sensors,big,applications
0,0.000050,0.000319,0.000100,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000106,0.000000
1,0.000211,0.000000,0.000000,0.0,0.0,0.000224,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000224,0.000000
2,0.000105,0.000444,0.000175,0.0,0.0,0.000296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000166,0.000647
3,0.000000,0.000000,0.000128,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000270
4,0.000342,0.000423,0.000228,0.0,0.0,0.000242,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000242,0.000906
5,0.000956,0.000145,0.000068,0.0,0.0,0.000145,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000867,0.000289
6,0.000204,0.001510,0.000102,0.0,0.0,0.000863,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000216,0.000647
7,0.000304,0.000292,0.000248,0.0,0.0,0.000526,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.001052,0.000234
8,0.000259,0.000274,0.000324,0.0,0.0,0.000137,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000137
9,0.000258,0.000136,0.000193,0.0,0.0,0.000409,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000545,0.000136

In [20]:
df = pd.DataFrame(selected_feature_all)
df = df.T
df.columns = folder_names
df

   Artificial Intelligence      Blockchain Internet of Things
0                      mit       financial            machine
1                     best    transactions              using
2                  network             way                add
3                     work    applications            devices
4                  systems           block               like
5                     risk        business           networks
6                    based            make          connected
7               algorithms          change           business
8                 software         digital               know
9                computing         private              smart
10                  people          public            network
11              technology           chain             sensor
12                    know          crypto            sensors
13                  humans  cryptocurrency                big
14                   given            peer       applications

In [21]:
df.to_csv (r'feature_extraction.csv', index = False, header=True)

In [26]:
vertical_stack = pd.concat([df_1, df_2, df_3], axis=1)
vertical_stack

,mit,best,network,work,systems,risk,based,algorithms,software,computing,...,networks,connected,business,know,smart,network,sensor,sensors,big,applications
0,0.0,0.000000,0.000000,0.0,0.0,0.000307,0.000362,0.000797,0.001227,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000106,0.000000
1,0.0,0.000056,0.000184,0.0,0.0,0.000011,0.000225,0.000084,0.000044,0.000089,...,0.000224,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000224,0.000000
2,0.0,0.000242,0.000400,0.0,0.0,0.000000,0.000000,0.000228,0.000121,0.000363,...,0.000296,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000166,0.000647
3,0.0,0.000397,0.000590,0.0,0.0,0.000114,0.000214,0.000188,0.000227,0.000114,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000270
4,0.0,0.000168,0.000053,0.0,0.0,0.000729,0.000053,0.000026,0.000112,0.000168,...,0.000242,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000242,0.000906
5,0.0,0.000233,0.000495,0.0,0.0,0.000116,0.000055,0.000385,0.000582,0.000466,...,0.000145,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000867,0.000289
6,0.0,0.000284,0.000134,0.0,0.0,0.000057,0.000080,0.000241,0.000284,0.000227,...,0.000863,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000216,0.000647
7,0.0,0.000000,0.000479,0.0,0.0,0.000000,0.000120,0.000000,0.000000,0.000253,...,0.000526,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.001052,0.000234
8,0.0,0.000246,0.000116,0.0,0.0,0.000246,0.000233,0.000116,0.000000,0.000000,...,0.000137,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000137
9,0.0,0.000070,0.000442,0.0,0.0,0.000332,0.000176,0.000166,0.000141,0.000292,...,0.000409,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000545,0.000136

In [27]:
vertical_stack.to_csv(r'feature_extration_with_frequency.csv', index = False, header = True)